AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  PipelineNotification:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          HAL: https://api.carddevops.co.za/telegram-text/1083240170

      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]